import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeftRight,
  ArrowUpDown,
  BarChart3,
  Braces,
  CalendarDays,
  Clock,
  Combine,
  CopyX,
  Crosshair,
  Database,
  FileArchive,
  FileJson,
  Filter,
  FunctionSquare,
  Gauge,
  GitBranch,
  GitMerge,
  Grid3x3,
  Group,
  HardDrive,
  HelpCircle,
  Layers,
  LayoutGrid,
  Link,
  ListChecks,
  Rows3,
  Scissors,
  Search,
  Settings,
  Sigma,
  Split,
  Table2,
  Terminal,
  TrendingUp,
  Type,
  Users,
  Wrench,
  Zap,
  Sparkles,
  type LucideIcon,
} from "lucide-react";

/**
 * Topic icons, named one by one on purpose. `import * as Icons` plus a dynamic
 * `Icons[meta.icon]` lookup forces the whole lucide set (~1500 icons) into the
 * bundle, because a bundler can't know which key is read. Listing the 41 the
 * registry actually uses keeps the rest out.
 *
 * Adding a topic with a new `icon` in the registry means adding it here too —
 * an unknown name falls back to Sparkles rather than breaking the page.
 */
const TOPIC_ICONS: Record<string, LucideIcon> = {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeftRight,
  ArrowUpDown,
  BarChart3,
  Braces,
  CalendarDays,
  Clock,
  Combine,
  CopyX,
  Crosshair,
  Database,
  FileArchive,
  FileJson,
  Filter,
  FunctionSquare,
  Gauge,
  GitBranch,
  GitMerge,
  Grid3x3,
  Group,
  HardDrive,
  HelpCircle,
  Layers,
  LayoutGrid,
  Link,
  ListChecks,
  Rows3,
  Scissors,
  Search,
  Settings,
  Sigma,
  Split,
  Table2,
  Terminal,
  TrendingUp,
  Type,
  Users,
  Wrench,
  Zap,
};

export function topicIcon(name: string): LucideIcon {
  return TOPIC_ICONS[name] ?? Sparkles;
}
