import type { PageMeta } from "@/types";
import type { PageId } from "@/store/useStore";

export const PAGES: Record<PageId, PageMeta> = {
  // ─── Foundations ──────────────────────────────────────────
  "series-vs-df": { id: "series-vs-df", title: "Series vs DataFrame", blurb: "The two building blocks of pandas", icon: "LayoutGrid", section: "Foundations",
    context: { what: "A Series is a labelled 1-D array. A DataFrame is a 2-D table — a dict of Series sharing one index.", why: "Every pandas function returns one of these two. Know their anatomy and you can predict the output of any operation.", how: "One column → Series. Multiple columns → DataFrame. Selecting, filtering, and aggregating all produce one or the other." } },
  "selection": { id: "selection", title: "Selection & Indexing", blurb: ".loc by label, .iloc by position", icon: "Crosshair", section: "Foundations",
    context: { what: ".loc uses labels (inclusive end). .iloc uses integers (exclusive end). [] is sugar for common cases.", why: "Confusing the two is the #1 pandas bug. The inclusive/exclusive difference trips up everyone at least once.", how: "df.loc[row_labels, col_labels] or df.iloc[row_ints, col_ints]. Each slot takes a scalar, list, slice, or mask." } },
  "comprehensions": { id: "comprehensions", title: "Comprehensions", blurb: "Pythonic list/dict/set building", icon: "Braces", section: "Foundations",
    context: { what: "A compact one-liner that builds a list, dict, or set from an iterable — [f(x) for x in items if cond].", why: "In pandas you'll use them for column name lists, renaming dicts, generating test data, and quick transformations before vectorization.", how: "List comp: [x**2 for x in range(5)]. Dict comp: {col: col.upper() for col in df.columns}. Set comp: {x % 3 for x in nums}." } },
  "lambda-map-filter": { id: "lambda-map-filter", title: "Lambda, map, filter", blurb: "Inline functions for quick transforms", icon: "FunctionSquare", section: "Foundations",
    context: { what: "lambda is an anonymous one-line function. map applies a function to every element. filter keeps elements where the function returns True.", why: "These are Python builtins that pandas leans on — .apply(lambda x: ...) is the most common escape hatch when built-ins don't fit.", how: "lambda x: x * 2 doubles a value. map(fn, iterable) → lazy iterator. filter(fn, iterable) → keeps truthy." } },
  "filtering": { id: "filtering", title: "Filtering Patterns", blurb: "Boolean masks, .query(), .isin(), .between()", icon: "Filter", section: "Foundations",
    context: { what: "Build a True/False Series (mask), pass to df[mask] to keep True rows. Multiple patterns exist.", why: "This is pandas' WHERE clause. Every data question starts with 'which rows do I want?'", how: "df[df['age'] > 30]. Combine with & (and), | (or), ~ (not). Alternatives: .query('age > 30'), .isin([...]), .between(lo, hi)." } },
  "sorting-topn": { id: "sorting-topn", title: "Sorting & Top-N", blurb: "sort_values, nlargest, nsmallest", icon: "ArrowUpDown", section: "Foundations",
    context: { what: "sort_values reorders rows. nlargest/nsmallest return the top or bottom N rows by a column — faster than sort + head.", why: "Ranking, leaderboards, finding extremes. sort_values handles multi-column tiebreaking; nlargest avoids sorting the entire frame.", how: "df.sort_values('score', ascending=False). df.nlargest(5, 'score'). Both preserve the original index labels." } },
  "basic-agg": { id: "basic-agg", title: "Basic Aggregation", blurb: "sum, mean, count, min, max and .agg()", icon: "Sigma", section: "Foundations",
    context: { what: "Aggregations collapse a column (or DataFrame) into a scalar. .agg() runs multiple at once.", why: "The foundation for every KPI: total revenue, average rating, row count, min/max price.", how: "df['price'].mean(). df[['price','qty']].agg(['sum','mean']). NaN is skipped by default." } },
  "dates": { id: "dates", title: "Working with Dates", blurb: "pd.to_datetime + the .dt accessor", icon: "CalendarDays", section: "Foundations",
    context: { what: "Parse strings into real timestamps with pd.to_datetime. Pull components with .dt.year, .dt.month, .dt.day_name().", why: "Time-based grouping (monthly revenue, weekly signups) requires actual datetime dtypes — strings won't sort or resample correctly.", how: "df['date'] = pd.to_datetime(df['date_str']). Then df['month'] = df['date'].dt.month. Works with .dt.strftime for custom formats." } },
  "missing-basics": { id: "missing-basics", title: "Missing Data Basics", blurb: "isna, dropna, fillna essentials", icon: "AlertTriangle", section: "Foundations",
    context: { what: "NaN = 'no value'. isna() detects, dropna() removes rows, fillna() replaces with a value.", why: "Raw data always has gaps. Aggregations silently skip NaN; merges introduce NaN for unmatched rows. You need a policy.", how: "df.isna().sum() → nulls per column. df.dropna(subset=['email']). df['score'].fillna(df['score'].median())." } },
  "chaining": { id: "chaining", title: "Chaining vs Intermediates", blurb: "Method chains for readable pipelines", icon: "Link", section: "Foundations",
    context: { what: "Each pandas method returns a new object, so you can chain: df.query(...).groupby(...).agg(...).reset_index().", why: "Chaining reads top-to-bottom like a recipe. Intermediates help when you need to inspect or reuse a mid-step result.", how: "Chain when the pipeline is linear. Break into variables when debugging, when a step is reused, or when the chain exceeds ~5 methods." } },

  // ─── Vectorization ────────────────────────────────────────
  "cut-qcut": { id: "cut-qcut", title: "Bucketing: pd.cut & pd.qcut", blurb: "Continuous → categorical", icon: "Scissors", section: "Vectorization",
    context: { what: "pd.cut splits by value boundaries. pd.qcut splits by quantiles (equal-count buckets).", why: "Turns a continuous column into labeled groups — essential for histograms, cohort analysis, and stratified sampling.", how: "pd.cut(df['age'], bins=[0,18,35,60,100], labels=['Youth','Adult','Middle','Senior']). pd.qcut(df['income'], q=4)." } },
  "vectorization": { id: "vectorization", title: "Vectorization Patterns", blurb: "Think in columns, not rows", icon: "Zap", section: "Vectorization",
    context: { what: "Vectorization = applying an operation to an entire column at once, using C-level loops under the hood.", why: "100-1000x faster than Python for-loops. The mental shift from 'loop over rows' to 'operate on columns' is the core pandas skill.", how: "df['total'] = df['price'] * df['qty']. np.where(cond, yes, no). str methods via .str. All avoid Python-level iteration." } },
  "loop-vs-vec": { id: "loop-vs-vec", title: "Loop vs Vectorized", blurb: "Side-by-side speed comparison", icon: "Gauge", section: "Vectorization",
    context: { what: "The same operation written as a for-loop vs a vectorized expression — with timing to prove the difference.", why: "Seeing a 100x speedup on a simple example makes the case for vectorization visceral and memorable.", how: "Loop: for i in range(len(df)): df.iloc[i, 2] = df.iloc[i, 0] * df.iloc[i, 1]. Vector: df['c'] = df['a'] * df['b']." } },

  // ─── GroupBy ──────────────────────────────────────────────
  "groupby-mental": { id: "groupby-mental", title: "GroupBy Mental Model", blurb: "Split → Apply → Combine", icon: "Group", section: "GroupBy",
    context: { what: "groupby partitions rows into buckets by a key. You then apply a function per bucket and pandas stitches the results.", why: "90% of analytics questions are groupby questions: avg score per batch, total sales per region, count per category.", how: "df.groupby('dept')['salary'].mean(). The groupby object is lazy — computation triggers on the aggregation call." } },
  "agg-patterns": { id: "agg-patterns", title: "Aggregation Patterns", blurb: "Named aggs, multiple functions, custom", icon: "ListChecks", section: "GroupBy",
    context: { what: "Beyond .mean(): named aggregations, per-column functions, and custom agg lambdas.", why: "Real reports need multiple metrics per group — avg + count + max in one call, with clean column names.", how: "df.groupby('cat').agg(avg_price=('price','mean'), n=('id','count')). Or .agg({'price': ['mean','max'], 'qty': 'sum'})." } },
  "transform-apply-filter": { id: "transform-apply-filter", title: "Transform vs Apply vs Filter", blurb: "Three ways to use groupby results", icon: "GitBranch", section: "GroupBy",
    context: { what: "transform: same-shape output (broadcasts back). apply: flexible (any shape). filter: keeps/drops whole groups.", why: "transform is for 'add a column relative to my group' (like % of group total). filter is for 'keep only groups meeting a condition'.", how: "df.groupby('g')['v'].transform('mean') → column of group means. .apply(custom_fn). .filter(lambda g: len(g) > 5)." } },
  "multi-groupby": { id: "multi-groupby", title: "Multi-level GroupBy", blurb: "Group by 2+ columns", icon: "Layers", section: "GroupBy",
    context: { what: "Pass a list to groupby for nested partitioning: groupby(['region','product']).", why: "When a single key isn't granular enough — e.g. monthly revenue PER region PER product line.", how: "Result has a MultiIndex. Use .reset_index() to flatten, or .unstack() to pivot the inner level into columns." } },
  "window-groups": { id: "window-groups", title: "Window Ops in Groups", blurb: "Rank, cumsum, pct_change per group", icon: "BarChart3", section: "GroupBy",
    context: { what: "Combine groupby with window functions: rank(), cumsum(), pct_change(), shift() — all scoped to each group.", why: "Ranked leaderboards per category, running totals per user, period-over-period growth per region.", how: "df.groupby('cat')['sales'].rank(method='dense'). .cumsum(). .pct_change(). Each returns a same-shape Series." } },

  // ─── Time Series ──────────────────────────────────────────
  "resample": { id: "resample", title: "Resampling", blurb: "Time-aware groupby (daily→weekly, etc.)", icon: "Clock", section: "Time Series",
    context: { what: "resample is groupby for time: bucket a datetime-indexed DataFrame by frequency (D, W, M, Q, Y).", why: "Convert raw timestamps into weekly sales, monthly active users, quarterly revenue — the standard time-series rollup.", how: "df.set_index('date').resample('W')['amount'].sum(). Requires a DatetimeIndex." } },
  "rolling": { id: "rolling", title: "Rolling Windows", blurb: "Moving averages and metrics", icon: "Activity", section: "Time Series",
    context: { what: "rolling(n) creates a sliding window of n rows, then applies an aggregation (mean, sum, std, etc.) to each window.", why: "Smooths noisy signals: 7-day moving average of daily sales, 30-day rolling retention, Bollinger bands.", how: "df['ma7'] = df['sales'].rolling(7).mean(). min_periods=1 allows partial windows at the start." } },
  "shift-lag": { id: "shift-lag", title: "Shift & Lag", blurb: "WoW, MoM, YoY growth", icon: "TrendingUp", section: "Time Series",
    context: { what: "shift(n) moves a column up or down by n rows. Paired with arithmetic, it gives period-over-period change.", why: "Week-over-week growth, month-over-month delta, year-over-year comparison — the bread and butter of business reporting.", how: "df['prev_week'] = df['sales'].shift(1). df['wow_growth'] = (df['sales'] - df['prev_week']) / df['prev_week'] * 100." } },

  // ─── Reshaping ────────────────────────────────────────────
  "pivot-table": { id: "pivot-table", title: "pivot_table", blurb: "Long → wide with aggregation", icon: "Grid3x3", section: "Reshaping",
    context: { what: "pivot_table creates a cross-tab: one column's values become rows, another's become columns, cells hold an aggregate.", why: "The most readable format for reports: region × month → revenue. Also the input format many chart libraries expect.", how: "pd.pivot_table(df, index='region', columns='month', values='revenue', aggfunc='sum', fill_value=0)." } },
  "crosstab": { id: "crosstab", title: "pd.crosstab", blurb: "Frequency table shortcut", icon: "Table2", section: "Reshaping",
    context: { what: "crosstab counts how often each combination of two categorical columns occurs. It's a shortcut for groupby + count + unstack.", why: "Contingency tables, chi-square prep, quick 'how many A×B' answers without three chained calls.", how: "pd.crosstab(df['region'], df['product']). Add margins=True for row/column totals, normalize='index' for row percentages." } },
  "melt": { id: "melt", title: "Melt: Wide → Long", blurb: "Unpivot columns into rows", icon: "ArrowLeftRight", section: "Reshaping",
    context: { what: "melt collapses multiple columns into two: variable_name and value. The inverse of pivot.", why: "Tidy data (one observation per row) is what groupby, seaborn, and ML pipelines expect. Wide data needs melting first.", how: "pd.melt(df, id_vars=['id'], value_vars=['jan','feb','mar'], var_name='month', value_name='sales')." } },

  // ─── Real-World Patterns ──────────────────────────────────
  "cohort": { id: "cohort", title: "Cohort Analysis", blurb: "Retention grids with pandas", icon: "Users", section: "Patterns",
    context: { what: "Group users by their signup month (cohort), then track what % are still active in months 1, 2, 3, …", why: "The gold-standard retention metric. Shows whether new users stick around — and whether product changes improve stickiness.", how: "1) Assign cohort month. 2) Compute period offset. 3) pivot_table(index=cohort, columns=period, values=user, aggfunc='nunique'). 4) Divide by cohort size." } },
  "funnel": { id: "funnel", title: "Funnel Analysis", blurb: "Conversion rates between stages", icon: "Filter", section: "Patterns",
    context: { what: "Track how many users pass through each stage (visit → signup → purchase) and where they drop off.", why: "Identifies the leakiest step. A 90% visit→signup rate but 5% signup→purchase rate tells you exactly where to focus.", how: "Group events by user, flag each stage reached, count users per stage, compute stage-over-stage conversion %." } },
  "normalize": { id: "normalize", title: "Normalizing Denormalized Data", blurb: "Split one fat table into linked tables", icon: "Split", section: "Patterns",
    context: { what: "Take a flat export (one row = all info jammed together) and split it into clean, linked tables.", why: "Denormalized CSVs duplicate data (customer name repeated on every order). Normalizing removes redundancy and inconsistency.", how: "1) Identify entity groups (orders, customers, products). 2) Extract unique entities. 3) Replace repeated data with IDs." } },
  "fact-dim": { id: "fact-dim", title: "Fact + Dimension Tables", blurb: "Star schema joins", icon: "Database", section: "Patterns",
    context: { what: "A fact table holds events/transactions (order_id, product_id, amount). Dimension tables hold attributes (product_id, name, category).", why: "The star schema is how every data warehouse is organized. Knowing it means you can navigate any company's data.", how: "pd.merge(facts, dim_product, on='product_id'). Chain multiple merges for star joins: facts → products → categories → regions." } },

  // ─── Joins & Combining ────────────────────────────────────
  "join-types": { id: "join-types", title: "Join Types Deep Dive", blurb: "inner, left, right, outer, cross", icon: "GitMerge", section: "Joins",
    context: { what: "Five join types control what happens to unmatched rows: inner drops both, left keeps left, right keeps right, outer keeps all, cross is cartesian.", why: "Choosing the wrong join silently loses or duplicates rows — the most common source of 'my numbers don't add up'.", how: "pd.merge(L, R, on='key', how='inner|left|right|outer'). Visualize with Venn diagrams for the mental model." } },
  "merge-join-concat": { id: "merge-join-concat", title: "merge vs join vs concat", blurb: "When to use which", icon: "Combine", section: "Joins",
    context: { what: "merge: SQL-style join on columns. join: merge on index. concat: stack along axis (rows or columns).", why: "All three combine DataFrames but for different shapes. Using the wrong one gives confusing NaN-filled results.", how: "merge for column-based keys. join for index-based keys. concat for appending rows (axis=0) or pasting columns (axis=1)." } },
  "merge-mechanics": { id: "merge-mechanics", title: "Merge Mechanics", blurb: "Indicator, suffixes, validate", icon: "Settings", section: "Joins",
    context: { what: "indicator=True adds a _merge column showing match status. suffixes rename colliding columns. validate catches unexpected duplicates.", why: "Debugging joins: 'why did my row count explode?' (many-to-many). 'which rows didn't match?' (indicator). 'which column is _x vs _y?' (suffixes).", how: "pd.merge(L, R, on='k', indicator=True, validate='one_to_many', suffixes=('_order','_product'))." } },
  "concat-patterns": { id: "concat-patterns", title: "concat Patterns", blurb: "Stack, append, keys, ignore_index", icon: "Rows3", section: "Joins",
    context: { what: "pd.concat stacks along axis 0 (rows) or 1 (columns). keys labels each source. ignore_index renumbers.", why: "Combining CSVs from multiple months, appending new data, pasting extra columns — all concat jobs.", how: "pd.concat([jan, feb, mar], ignore_index=True). pd.concat([df, new_cols], axis=1). keys=['jan','feb'] adds a level." } },

  // ─── I/O & Performance ────────────────────────────────────
  "json-df": { id: "json-df", title: "JSON → DataFrame", blurb: "Nested JSON flattening", icon: "FileJson", section: "I/O",
    context: { what: "pd.read_json for flat JSON. pd.json_normalize for nested structures — flattens dicts/lists into columns.", why: "APIs return JSON, not CSV. Nested payloads (order → items → product) need flattening before analysis.", how: "pd.json_normalize(data, record_path='items', meta=['order_id','customer']). Dot notation for nested keys." } },
  "chunking": { id: "chunking", title: "Reading Large Files", blurb: "chunksize for memory-safe processing", icon: "HardDrive", section: "I/O",
    context: { what: "pd.read_csv(..., chunksize=100000) returns an iterator of DataFrames instead of loading everything at once.", why: "A 10GB CSV won't fit in 16GB RAM. Chunking lets you process, filter, or aggregate in pieces.", how: "for chunk in pd.read_csv('big.csv', chunksize=100_000): results.append(chunk.groupby('cat')['val'].sum()). Then pd.concat(results).groupby(level=0).sum()." } },
  "parquet-csv": { id: "parquet-csv", title: "Parquet vs CSV", blurb: "Columnar storage for speed", icon: "FileArchive", section: "I/O",
    context: { what: "Parquet is a columnar binary format. It stores dtypes, compresses well, and reads 5-50x faster than CSV.", why: "CSV re-parses everything on every read (slow, no types). Parquet reads only the columns you need and preserves dtypes.", how: "df.to_parquet('data.parquet'). pd.read_parquet('data.parquet', columns=['name','score']). Requires pyarrow or fastparquet." } },
  "eval-query": { id: "eval-query", title: "eval() & query()", blurb: "String expressions for speed", icon: "Terminal", section: "I/O",
    context: { what: "df.query('price > 100 and category == \"Electronics\"') filters with a string expression. df.eval('margin = revenue - cost') adds a column.", why: "For large DataFrames, eval/query can be faster because they avoid creating intermediate boolean arrays.", how: "df.query('age > @threshold') — the @ prefix references Python variables. eval supports +, -, *, /, >, <, and, or." } },
  "index-speed": { id: "index-speed", title: "Indexing for Speed", blurb: "set_index + .loc for O(1) lookups", icon: "Zap", section: "I/O",
    context: { what: "Setting a column as index creates a hash-based lookup. .loc on an indexed column is O(1) instead of O(n).", why: "If you repeatedly filter by the same column (user_id, date), indexing it once makes every subsequent lookup instant.", how: "df = df.set_index('user_id'). Then df.loc['U123'] is a hash lookup. For sorted indexes, .searchsorted is even faster." } },

  // ─── Data Quality ─────────────────────────────────────────
  "mcar-mar-mnar": { id: "mcar-mar-mnar", title: "Classifying Missingness", blurb: "MCAR, MAR, MNAR patterns", icon: "HelpCircle", section: "Quality",
    context: { what: "MCAR: missing completely at random. MAR: missingness depends on other columns. MNAR: missingness depends on the missing value itself.", why: "The strategy you pick (drop, fill, model) depends on WHY data is missing. MNAR requires domain knowledge; MCAR is safe to drop.", how: "Test MCAR: compare means of complete vs incomplete groups. MAR: check if missingness correlates with other columns. MNAR: needs external info." } },
  "viz-missing": { id: "viz-missing", title: "Visualizing Missingness", blurb: "Heatmaps and bar charts of nulls", icon: "BarChart3", section: "Quality",
    context: { what: "A matrix heatmap where rows are records and columns are features — white cells are present, colored cells are missing.", why: "Patterns pop out visually: a block of missing rows means a data pipeline outage. A column that's 80% null might not be worth keeping.", how: "msno.matrix(df) from the missingno library. Or df.isna().sum().plot.bar(). Or sns.heatmap(df.isna(), cbar=False)." } },
  "imputation": { id: "imputation", title: "Imputation Strategies", blurb: "Mean, median, mode, forward-fill, interpolate", icon: "Wrench", section: "Quality",
    context: { what: "Replace NaN with a computed value: column mean/median/mode, forward-fill (last known value), or linear interpolation.", why: "Dropping rows wastes data. Smart imputation preserves sample size while introducing minimal bias.", how: "df['temp'].fillna(method='ffill'). df['score'].fillna(df['score'].median()). df['price'].interpolate(method='linear')." } },
  "duplicates": { id: "duplicates", title: "Duplicates", blurb: "duplicated, drop_duplicates, subset, keep", icon: "CopyX", section: "Quality",
    context: { what: "duplicated() flags repeat rows. drop_duplicates() removes them. subset checks specific columns; keep controls which copy survives.", why: "Duplicate rows inflate counts, averages, and sums. They sneak in from faulty joins, re-imports, and append-without-dedup.", how: "df.duplicated(subset=['email'], keep='first'). df.drop_duplicates(subset=['order_id']). keep=False marks ALL copies." } },
  "str-accessor": { id: "str-accessor", title: "The .str Accessor", blurb: "Vectorized string methods", icon: "Type", section: "Quality",
    context: { what: ".str exposes Python string methods on a whole column: .lower(), .contains(), .split(), .replace(), .strip(), .extract().", why: "Text cleaning at C speed — no Python loop. Casing, whitespace, splitting emails, extracting regex groups.", how: "df['email'].str.split('@').str[1] → domain. df['name'].str.contains('Inc', case=False) → boolean mask." } },
  "regex-extract": { id: "regex-extract", title: "Regex for Extraction", blurb: ".str.extract with capture groups", icon: "Search", section: "Quality",
    context: { what: ".str.extract(r'pattern') pulls named/numbered capture groups into new columns.", why: "When split isn't enough — phone number formats, embedded IDs, log file parsing, URL parameters.", how: "df['phone'].str.extract(r'(\\d{3})-(\\d{3})-(\\d{4})'). Named groups: r'(?P<area>\\d{3})-...' create named columns." } },
  "outliers": { id: "outliers", title: "Outlier Detection", blurb: "IQR, Z-score, visual checks", icon: "AlertCircle", section: "Quality",
    context: { what: "Values far from the center. IQR method: outside [Q1 - 1.5·IQR, Q3 + 1.5·IQR]. Z-score: |z| > 3.", why: "Outliers skew means, inflate variance, and break ML models. Detect first, then decide: remove, cap, or keep.", how: "Q1, Q3 = df['val'].quantile([.25, .75]). IQR = Q3 - Q1. mask = (df['val'] < Q1 - 1.5*IQR) | (df['val'] > Q3 + 1.5*IQR)." } },
};

export const SECTIONS: Array<{ label: string; pages: PageId[] }> = [
  { label: "Foundations", pages: ["series-vs-df","selection","comprehensions","lambda-map-filter","filtering","sorting-topn","basic-agg","dates","missing-basics","chaining"] },
  { label: "Vectorization", pages: ["cut-qcut","vectorization","loop-vs-vec"] },
  { label: "GroupBy", pages: ["groupby-mental","agg-patterns","transform-apply-filter","multi-groupby","window-groups"] },
  { label: "Time Series", pages: ["resample","rolling","shift-lag"] },
  { label: "Reshaping", pages: ["pivot-table","crosstab","melt"] },
  { label: "Patterns", pages: ["cohort","funnel","normalize","fact-dim"] },
  { label: "Joins", pages: ["join-types","merge-join-concat","merge-mechanics","concat-patterns"] },
  { label: "I/O & Perf", pages: ["json-df","chunking","parquet-csv","eval-query","index-speed"] },
  { label: "Data Quality", pages: ["mcar-mar-mnar","viz-missing","imputation","duplicates","str-accessor","regex-extract","outliers"] },
];
